### ISSUE TITLE
AES with token restricted and HLS cannot work

### ISSUE THREAD

**Issue by monstatw** [southworkscom/azure-sdk-for-media-services-java-samples#2]
[http://goo.gl/VV0BEX](http://goo.gl/VV0BEX)
This is the URL in which I generated a sample video using AMS and play on AMP demo page.
One can clearly see that it is ok for playback of both DASH and Smooth. But when to select the format in HLS, the key request would response with 401 (unauthorized).

**Comment by mconverti** [comment]
@monstatw 

The problem with HLS + AES with Token Restriction, is that Safari handles HLS playlist and key retrieval within the native stack and there is no easy way for the player to intercept the key request and add in Token into the 2nd level HLS Playlist. That's why you get the 401 (unauthorized).

In the following article you can find a proposed solution by [@mingfeiy](https://twitter.com/mingfeiy) to make this work.

https://azure.microsoft.com/en-us/blog/how-to-make-token-authorized-aes-encrypted-hls-stream-working-in-safari/

Hope it helps!
Mariano

**Comment by monstatw** [comment]
Thanks for the reply, I understand the problem now.
